"""Collection contract derived from PIMEC Method Implementation Guide, v1.0."""

def fields(spec):
    result = []
    for item in spec.split(";"):
        parts = item.split("|")
        result.append({"key": parts[0], "label": parts[1], "type": parts[2] if len(parts) > 2 else "text",
                       "options": parts[3].split(",") if len(parts) > 3 else []})
    return result


def register(key, title, hint, spec):
    return {"key": key, "title": title, "hint": hint, "fields": fields(spec)}


STAGES = [
    {"title": "Frame and align", "period": "Week 1", "output": "Engagement charter", "gate": "Sponsor approves the charter; required information and decision makers are accessible.", "registers": [
        register("charter", "Engagement charter", "Record the observable gap. Separate facts, opinions, and suspected causes. Use one charter per case.",
                 "client|Client / business;problem|Observable problem and who is affected|textarea;started|When it started;facts|Facts and supporting evidence|textarea;opinions|Opinions and suspected causes|textarea;tried|What has been tried|textarea;urgency|Why action is urgent;outcome|Intended outcome and success measures|textarea;scope|Site / process / product family and included work|textarea;excluded|Excluded work|textarea;period|Planning period;constraints|Budget, staffing, and other constraints|textarea;dependencies|Dependencies|textarea;authority|Sponsor authority and available resources|textarea;currency|Reporting currency (one per case);handover|Planned handover|date"),
        register("owners", "Responsibilities and decision rights", "Include sponsor, process owner, PIMEC lead, Finance, workstream owners and data owners. One accountable person per outcome.",
                 "role|Role;person|Accountable person;outcome|Owned outcome;authority|Decision rights;backup|Backup"),
        register("measures", "Baseline and performance measures", "Use consistent definitions, units and periods. Enter actuals only for comparable periods; explain volume or mix effects.",
                 "name|Measure;definition|Definition;unit|Unit;source|Source / evidence;owner|Owner;frequency|Review frequency;period|Baseline period;baseline|Baseline|number;target|Target|number;actual|Actual|number;actual_period|Actual period;direction|Better direction|select|Higher,Lower;quality|Data reliability|select|Provisional,Validated;context|Comparability, volume / mix / staffing adjustments|textarea"),
        register("rhythm", "Review rhythm and sessions", "Plan kickoff, diagnosis, prioritization, progress, benefit and handover sessions. Governance starts now.",
                 "name|Review / session;frequency|Frequency;date|Next date|date;owner|Chair / owner;attendees|Participants;purpose|Decisions / acceptance criteria;record|Action, risk, decision and evidence location") ]},
    {"title": "Diagnose and quantify", "period": "Weeks 2–3", "output": "Diagnostic report and opportunity register", "gate": "Operations and Finance accept the evidence, causes, constraints and opportunity calculations.", "registers": [
        register("datasets", "Data requests and validation", "Request monthly P&L, customer/product contribution, orders/shipments, labor/output, scrap/rework, inventory, purchasing/supplier delivery, downtime, staffing and instructions only for a defined purpose.",
                 "name|Dataset;purpose|Analytical purpose;owner|Data owner;period|Period;unit|Units;source|Evidence reference;status|Collection status|select|Requested,Received,Validated;checks|Period match, missing / duplicate rows, timestamps, returns, credits, cancellations, rework and reconciliation checks|textarea;limitations|Limitations and effect on conclusions|textarea"),
        register("observations", "Process observations", "Follow real work with employees, including normal cases and exceptions. Evidence must come from the actual operation.",
                 "process|Order / product / service and process step;date|Observation date|date;observer|Observer;processing|Processing minutes|number;waiting|Waiting minutes|number;queue|Queue and handoffs;exceptions|Rework, shortages, missing information, approvals or workarounds|textarea;conditions|Normal / exception conditions;source|Evidence / process map reference"),
        register("causes", "Root-cause hypotheses", "Use 5 Whys, process maps, cause-and-effect or comparisons. A hypothesis remains unproven until tested.",
                 "problem|Problem / constraint;hypothesis|Proposed cause;method|Test method;test|Test and comparison|textarea;evidence|Results and evidence|textarea;conclusion|Conclusion|select|Untested,Supported,Rejected,Inconclusive;owner|Owner;next|Next test / action"),
        register("opportunities", "Loss and opportunity register", "Enter nonnegative quantities and rates for one stated period. Profit, cash, capacity, service and risk remain separate. Use the same unit within each category for Pareto comparisons. For service and risk enter assessed magnitude as quantity and 1 as rate.",
                 "id|Opportunity ID;name|Loss / opportunity;segment|Customer / product / department / shift / machine / supplier / reason;category|Benefit category|select|Profit,Cash,Capacity,Service,Risk;unit|Result unit (currency, hours, etc.);period|Measurement period;quantity_low|Avoidable quantity — low|number;quantity_high|Avoidable quantity — high|number;rate_low|Relevant unit cost / contribution — low|number;rate_high|Relevant unit cost / contribution — high|number;mechanism|Calculation basis and financial mechanism|textarea;assumptions|Demand, capacity, cost and sustainability assumptions|textarea;evidence|Source / root-cause evidence;owner|Owner;overlap|Shared benefit / overlap group (if any)") ]},
    {"title": "Prioritize and choose", "period": "Week 4", "output": "Prioritized roadmap and workstream plans", "gate": "Selected initiatives have one owner, measurable targets, funding, capacity and a realistic approved plan.", "registers": [
        register("initiatives", "Initiatives and roadmap", "Score impact and feasibility from 1 (low) to 5 (high). Feasibility is higher for manageable cost, skills, time and disruption. Mean scores support judgment; they do not approve work.",
                 "id|Initiative ID;opportunity|Linked opportunity IDs;name|Defined change / action;problem|Problem and evidence|textarea;result|Measurable operating target;owner|Accountable owner;type|Work type|select|Immediate,Focused project,Structural;customer|Customer / financial impact (1–5)|score;delivery|Delivery / quality impact (1–5)|score;risk|Risk reduction / strategic impact (1–5)|score;resources_score|Investment / resource feasibility (1–5)|score;skills|Skills / technical feasibility (1–5)|score;time|Time / dependency feasibility (1–5)|score;resources|Resources, available owner capacity and protected customer commitments|textarea;spend|Required spending|number;funding|Funding / approval evidence;dependencies|Dependencies and how resolved|textarea;milestones|Milestones and review dates|textarea;date|Target date|date;risks|Risks and mitigations|textarea;selection|Decision|select|Proposed,Selected,Deferred;decision|Approval or deferral reason and decision maker") ]},
    {"title": "Execute and mobilize", "period": "Weeks 5–10", "output": "Implemented changes and pilot evidence", "gate": "The change works under representative conditions, with evidence, updated procedures, trained users and an ongoing owner.", "registers": [
        register("actions", "Action tracker", "A meeting is not completion. Completed actions require evidence that the change is implemented.",
                 "initiative|Initiative ID;action|Action;owner|Owner;date|Due date|date;status|Status|select|Planned,In progress,Blocked,Complete;evidence|Completion evidence;barrier|Barrier / support needed;correction|Corrective action and escalation"),
        register("pilots", "Pilots and baseline comparisons", "Record representative conditions and alternative explanations. Track defects and work-in-process alongside throughput.",
                 "initiative|Initiative ID;scope|Pilot scope and conditions|textarea;kickoff|Kickoff, participants and concerns|textarea;measure|Measure / unit;baseline|Baseline|number;actual|Pilot result|number;period|Comparable baseline / pilot periods;factors|Volume, mix, staffing, hours, material, equipment and demand|textarea;consequences|Quality, WIP and unintended consequences|textarea;evidence|Evidence;decision|Adjust / expand decision and rationale|textarea;owner|Ongoing owner;standard|Updated procedure and training reference"),
        register("daily", "Daily management", "Review yesterday, today, the largest gap, action and required support.",
                 "date|Review date|date;owner|Review owner;yesterday|Yesterday's result;today|Today's plan;gap|Largest gap;action|Action being taken;support|Support / decision needed") ]},
    {"title": "Govern and validate", "period": "Throughout", "output": "Performance dashboard, benefits register and decisions", "gate": "Results and calculations are credible; Finance has reviewed financial claims; material issues have owners and plans.", "registers": [
        register("benefits", "Benefits register", "Identified = estimated; Approved = accepted; Implemented = operating; Realized = observed; Validated = reviewed. Separate achieved-to-date and estimated annualized amounts. Overlapping claims are excluded from totals until allocated once.",
                 "initiative|Initiative ID;name|Benefit;category|Category|select|Profit,Cash,Capacity,Service,Risk;unit|Unit;period|Achieved-to-date period;baseline|Baseline;target|Target;actual|Actual;amount|Benefit achieved to date|number;annualized|Estimated annualized benefit|number;calculation|Calculation and assumptions|textarea;evidence|Supporting evidence;owner|Accountable owner;status|Stage|select|Identified,Approved,Implemented,Realized,Validated;finance|Finance reviewer (required for Profit / Cash);reviewer|Results reviewer;review_date|Validation date|date;overlap|Shared benefit / overlap group;allocation|Allocation / de-duplication evidence"),
        register("decisions", "Decisions, risks and corrective actions", "Record commitments, late milestones, barriers and changes in expected benefits. Escalate matters beyond owner authority.",
                 "issue|Issue / risk / slippage;cause|Execution, assumptions or changed conditions;decision|Decision / corrective action;owner|Decision owner;date|Deadline|date;status|Status|select|Open,Assigned,Resolved;evidence|Decision evidence;escalation|Escalation route") ]},
    {"title": "Transfer and sustain", "period": "Weeks 11–12 and follow-up", "output": "Handover pack and control plan", "gate": "Process owner and sponsor accept procedures, demonstrated capability, controls, authority and remaining actions.", "registers": [
        register("standards", "Standard work", "Link approved procedures, photographs or examples. Describe how work should actually be done.",
                 "process|Process;owner|Owner;sequence|Sequence, roles and inputs|textarea;checks|Quality checks and timing|textarea;exceptions|Exceptions and escalation|textarea;evidence|Procedure / checklist reference"),
        register("training", "Demonstrated capability", "Attendance alone is insufficient. Confirm ability to perform work, update measures, interpret gaps, act and escalate.",
                 "person|Owner / employee;backup|Backup;process|Process / role;date|Assessment date|date;demonstration|Demonstrated tasks and evidence|textarea;assessor|Assessor;result|Result|select|Pending,Needs practice,Demonstrated"),
        register("controls", "Control plan", "Define intervention triggers and responses so the client can act without routine PIMEC intervention.",
                 "measure|Measure;owner|Owner;frequency|Review frequency;target|Target;trigger|Intervention trigger;response|Required response;escalation|Escalation route"),
        register("audits", "Process audits and follow-up", "Check process adherence as well as outcomes. Review sustained results, benefit validity and changes to ownership or conditions at 30, 60 and 90 days, adjusted to the engagement.",
                 "date|Review date|date;owner|Reviewer;type|Review|select|Process audit,30-day,60-day,90-day,Other;adherence|Process adherence evidence|textarea;results|Sustained performance and benefit validity|textarea;changes|Changed ownership / conditions;actions|Corrective actions, owner and due date|textarea"),
        register("acceptance", "Formal handover acceptance", "Record actual sponsor and process-owner acceptance. An agent cannot grant approval on their behalf.",
                 "sponsor|Sponsor;process_owner|Process owner;date|Acceptance date|date;evidence|Acceptance evidence;readiness|Procedures, training, reporting and authority confirmed|textarea;remaining|Remaining actions with owners and due dates|textarea") ]}
]

GATE_FIELDS = fields("status|Readiness|select|Not ready,In review,Accepted;reviewer|Approver(s);date|Decision date|date;evidence|Approval evidence;remaining|Open conditions / remaining actions|textarea")
SCHEMA = {"version": 1, "source": "PIMEC Method Implementation Guide, 2 October 2026, v1.0", "stages": STAGES, "gate_fields": GATE_FIELDS}
